# Generated by Django 5.2.3 on 2025-06-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
